### ISSUE TITLE
初始化出现1100

### ISSUE THREAD

**Issue by Go5303** [zscorpio/web-wechat#2]
["BaseResponse"]=> array(2) { ["Ret"]=> int(1100) ["ErrMsg"]=> string(0) "" } ["Count"]=> int(0) ["ContactList"]=> array(0) { } ["SyncKey"]=> array(2) { ["Count"]=> int(0) ["List"]=> array(0) { } } ["User"]=> array(19) { ["Uin"]=> int(0) ["UserName"]=> string(0) "" ["NickName"]=> string(0) "" ["HeadImgUrl"]=> string(0) "" ["RemarkName"]=> string(0) "" ["PYInitial"]=> string(0) "" ["PYQuanPin"]=> string(0) "" ["RemarkPYInitial"]=> string(0) "" ["RemarkPYQuanPin"]=> string(0) "" ["HideInputBarFlag"]=> int(0) ["StarFriend"]=> int(0) ["Sex"]=> int(0) ["Signature"]=> string(0) "" ["AppAccountFlag"]=> int(0) ["VerifyFlag"]=> int(0) ["ContactFlag"]=> int(0) ["WebWxPluginSwitch"]=> int(0) ["HeadImgFlag"]=> int(0) ["SnsFlag"]=> int(0) } ["ChatSet"]=> string(0) "" ["SKey"]=> string(0) "" ["ClientVersion"]=> int(0) ["SystemTime"]=> int(0) ["GrayScale"]=> int(0) ["InviteStartCount"]=> int(0) ["MPSubscribeMsgCount"]=> int(0) ["MPSubscribeMsgList"]=> array(0) { } ["ClickReportInterval"]=> int(0)

**Comment by zscorpio** [comment]
好多年前了...已经不兼容了...

**Comment by Go5303** [comment]
有没有最新的，我最近需要搞一个，谢谢。

**Comment by Go5303** [comment]
1100这个问题困扰我很久了，部分微信是没有问题的，正常请求，但是部分出现1100，很是蛋疼。

**Comment by zscorpio** [comment]
不再维护
